"""empty message

Revision ID: ba6f04918c71
Revises: c8f0aec2f0f7
Create Date: 2016-02-26 04:42:29.294714

"""

# revision identifiers, used by Alembic.
revision = 'ba6f04918c71'
down_revision = 'c8f0aec2f0f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('sex', sa.String(length=20), nullable=True))
    op.drop_column('myprofile', 'option')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('option', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('myprofile', 'sex')
    ### end Alembic commands ###
