"""empty message

Revision ID: da385d382128
Revises: ba6f04918c71
Create Date: 2016-02-26 07:55:49.118917

"""

# revision identifiers, used by Alembic.
revision = 'da385d382128'
down_revision = 'ba6f04918c71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('high_score', sa.Integer(), nullable=True))
    op.add_column('myprofile', sa.Column('profile_add_on', sa.String(length=120), nullable=True))
    op.add_column('myprofile', sa.Column('tdollars', sa.Integer(), nullable=True))
    op.add_column('myprofile', sa.Column('user_name', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('myprofile', 'user_name')
    op.drop_column('myprofile', 'tdollars')
    op.drop_column('myprofile', 'profile_add_on')
    op.drop_column('myprofile', 'high_score')
    ### end Alembic commands ###
